portfolios:
  - title: 'AI 성경 RAG기반 챗봇'
    description: '성경 31,091개 구절을 임베딩 시킨 elasticSearch와 LLM(AI)을, RAG기반으로 연계한 서비스, 출처 지원, 이전 대화 (30일치) 지원, 임베딩(re-index) 처리, Ensemble Retriever(keyword, vector, semantic, hierarchy), score min-max 정규화, 채팅어, 비속어 차단, 반응형'
    tech: 'FastAPI, Elasticsearch(vectorstore), ORM(chatting), Jinja2, LangChain, HuggingFace, RAG, nori_tokenizer, konlpy(okt), React, vite, TypeScript, chakra-ui'
    url: 'https://a1.mkeasy.kro.kr/rag2/'
    time: '1s'
    images:
      - 'image/portfolio/ai_bible/ai_bible_01.jpg'
      - 'image/portfolio/ai_bible/ai_bible_03.jpg'

  - title: '한국렌탈'
    description: '렌탈고객 포털 사이트, 기존 .NET 서비스를 java로 개편, 사내 ERP 연동, BackOffice 제공'
    tech: 'Springboot, Thymeleaf, MyBatis, MSSQL, jQuery, dxGrid(devExpress)'
    url: 'https://www.krsmart.com'
    time: '1s'
    images:
      - 'image/portfolio/krsmart/krsmart_01.jpg'
      - 'image/portfolio/krsmart/krsmart_02.jpg'
      - 'image/portfolio/krsmart/krsmart_03.jpg'
      - 'image/portfolio/krsmart/krsmart_04.jpg'
      - 'image/portfolio/krsmart/krsmart_05.jpg'
      - 'image/portfolio/krsmart/krsmart_06.jpg'
      - 'image/portfolio/krsmart/krsmart_07.jpg'
      - 'image/portfolio/krsmart/krsmart_08.jpg'
      - 'image/portfolio/krsmart/krsmart_09.jpg'
      - 'image/portfolio/krsmart/krsmart_10.jpg'
      - 'image/portfolio/krsmart/krsmart_11.jpg'
      - 'image/portfolio/krsmart/krsmart_12.jpg'
      - 'image/portfolio/krsmart/krsmart_13.jpg'
      - 'image/portfolio/krsmart/krsmart_14.jpg'

  - title: 'OROUND(e커머스)'
    description: '상품관리, 통계, 정산 기능 개발'
    tech: 'Springboot, Next.js, JPA, QueryDSL, MyBatis, MySQL, CQRS'
    url: 'https://oround.com'
    time: '1s'
    images:
      - 'image/portfolio/oround/oround_01.jpg'
      - 'image/portfolio/oround/oround_02.jpg'
      - 'image/portfolio/oround/oround_03.jpg'
      - 'image/portfolio/oround/oround_04.jpg'
      - 'image/portfolio/oround/oround_05.jpg'

  - title: '리쿠르트 통계'
    description: '월간 직원연락망.xls 분석으로 만든 통계용 챠트, 반응형'
    tech: 'Flask, pandas, matplotlib, seaborn'
    url: 'https://a1.mkeasy.kro.kr/hr_list'
    time: '1s'
    images: 
      - 'image/portfolio/recruite/월별 입사자수.jpg'
      - 'image/portfolio/recruite/전체 입사자수 .vs. 퇴사자수.jpg'
      - 'image/portfolio/recruite/월별 퇴사자수.jpg'
      - 'image/portfolio/recruite/부서별 입사율 .vs. 퇴사율.jpg'
      - 'image/portfolio/recruite/직급별 입사자수,퇴사자수.jpg'
      - 'image/portfolio/recruite/전체 입사율, 퇴사율.jpg'
      - 'image/portfolio/recruite/직급별 바로 퇴사자수.jpg'
      - 'image/portfolio/recruite/부서별 입사자수 .vs. 퇴사자수.jpg'
      - 'image/portfolio/recruite/월별 고용 성장율.jpg'
      - 'image/portfolio/recruite/인력 변경율, 채용 성공율.jpg'
      - 'image/portfolio/recruite/부서별 바로 퇴사자수.jpg'

  - title: '파일 서버'
    description: '개인용 파일 서버(임베딩 처리 및 다운로드) 및 SSO 인증 처리, 반응형'
    tech: 'FastAPI, pydantic, keycloak, cookie, redis, middleware'
    url: 'https://a1.mkeasy.kro.kr/v1'
    time: '1s'
    images:
      - 'image/portfolio/fileserver/fileserver_02.jpg'
      - 'image/portfolio/fileserver/fileserver_01.jpg'

  - title: '명언 카드'
    description: '명언({count_quotes}개) API 서버 구현 및 연동, 한글 해석, 공유기능, 명언 크롤링, 카카오 링크 클릭시 타사 브라우져 전환 기능, 반응형'
    tech: 'FastAPI, SQLAlchemy, PostgreSQL, websocket, mqtt, deep-L translator'
    url: 'https://a1.mkeasy.kro.kr/chat/'
    time: '1s'
    images:
      - 'image/portfolio/quotes/quotes_01.jpg'

  - title: '송악읍 과거 날씨'
    description: '공공데이터 시계열 자료 사용, 10년치 자료 분석 (총 {count_weather_data}건), 반응형'
    tech: '고속 데이터 전처리, FastAPI, pandas, SQLAlchemy, PostgreSQL, vega-lite'
    url: 'https://a1.mkeasy.kro.kr/past-weather'
    time: '1s'
    images:
      - 'image/portfolio/pastweather/pastweather_01.jpg'

  - title: 'ERP 화면'
    description: 'React를 사용해 다중탭 화면 구성'
    tech: 'React, vite, TypeScript, tailwindcss, shadcn, recoil, styled-components'
    url: 'https://a1.mkeasy.kro.kr/erp'
    time: '1s'
    images:
      - 'image/portfolio/erp_ui/erp_01.jpg'
      - 'image/portfolio/erp_ui/erp_02.jpg'
      - 'image/portfolio/erp_ui/erp_00.jpg'

  - title: '달력 한장'
    description: '출력용 일년치 달력 (한국 휴일 표시)'
    tech: 'React, vite, TypeScript, tailwindcss, nestjs(BFF) API'
    url: 'https://a1.mkeasy.kro.kr/calendar'
    time: '1s'
    images:
      - 'image/portfolio/calendar/cal_01.jpg'
      - 'image/portfolio/calendar/cal_02.jpg'