personal_projects:
  - title: '리쿠르트 통계'
    description: '월간 직원연락망.xls 분석으로 만든 통계용 챠트'
    tech: 'Flask, pandas, matplotlib, seaborn'
    image: 'image/recrute-thumbnail.png'
    url: 'https://a1.mkeasy.kro.kr/hr_list'

  - title: '파일 서버'
    description: '개인용 파일 서버 및 SSO 인증 처리'
    tech: 'FastAPI, pydantic, keycloak, cookie, redis, middleware'
    image: 'image/file-server-thumbnail.png'
    url: 'https://a1.mkeasy.kro.kr/v1'

  - title: '명언 카드'
    description: '명언({count_quotes}개) API 서버 구현 및 연동, 한글 해석, share 제공'
    tech: 'FastAPI, SQLAlchemy, PostgreSQL, websocket, mqtt, deep-L translator'
    image: 'image/famous-quotes-thumbnail.png'
    url: 'https://a1.mkeasy.kro.kr/chat/'

  - title: '송악읍 과거 날씨'
    description: '공공데이터 시계열 자료 사용, 10년치 자료 분석 (총 {count_weather_data}건)'
    tech: '고속 데이터 전처리, FastAPI, pandas, SQLAlchemy, PostgreSQL, vega-lite'
    image: 'image/past-weather-thumbnail.png'
    url: 'https://a1.mkeasy.kro.kr/past-weather'

  - title: 'ERP 화면'
    description: 'React를 사용해 다중탭 화면 구성'
    tech: 'React, vite, TypeScript, tailwindcss, shadcn, recoil, styled-components'
    image: 'image/react-erp.png'
    url: 'https://a1.mkeasy.kro.kr/erp'

  - title: '달력 한장'
    description: '출력용 일년치 달력 (한국 휴일 표시)'
    tech: 'React, vite, TypeScript, tailwindcss, nestjs(BFF) API'
    image: 'image/calendar-thumbnail.png'
    url: 'https://a1.mkeasy.kro.kr/calendar'

  - title: 'ES를 이용한 RAG기반 챗봇'
    description: 'React -> FastAPI -> RAG -> LangChain -> LLM, ES 연계'
    tech: 'FastAPI, Elasticsearch, Jinja2, LangChain, HuggingFace, RAG, React, vite, TypeScript, tailwindcss'
    image: 'image/rag2-thumbnail.png'
    url: 'https://a1.mkeasy.kro.kr/rag2/'

participated_projects:
  - title: '한국렌탈'
    description: '렌탈고객 포털 사이트, 기존 .NET 서비스를 java로 개편, 사내 ERP 연동, BackOffice 제공'
    tech: 'Springboot, Thymeleaf, MyBatis, MSSQL, jQuery, dxGrid(devExpress)'
    image: 'image/krsmart.png'
    url: 'https://www.krsmart.com'

  - title: 'e커머스'
    description: '상품관리, 통계, 정산 기능 개발'
    tech: 'Springboot, Next.js, JPA, QueryDSL, MyBatis, MySQL, CQRS'
    image: 'image/oround.png'
    url: 'https://oround.com'
