"""Create MinoLikes table

Revision ID: 3d6629a120c3
Revises: e453b3991372
Create Date: 2024-11-08 21:43:01.721812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d6629a120c3'
down_revision: Union[str, None] = 'e453b3991372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MinoLikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['MinoQuotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quote_id', name='uq_mino_like_user_quote')
    )
    op.create_index('idx_mino_like_created_at', 'MinoLikes', ['created_at'], unique=False)
    op.create_index('idx_mino_like_hash', 'MinoLikes', [sa.text('md5(user_id || CAST(quote_id AS VARCHAR))')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mino_like_hash', table_name='MinoLikes')
    op.drop_index('idx_mino_like_created_at', table_name='MinoLikes')
    op.drop_table('MinoLikes')
    # ### end Alembic commands ###
