"""Add new columns to MinoQuote

Revision ID: b429e7cc28d3
Revises: 
Create Date: 2024-11-01 13:16:23.190684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b429e7cc28d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'MinoLikes',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('user_id', sa.String(length=256), nullable=False),
        sa.Column('quote_id', sa.Integer(), sa.ForeignKey('MinoQuotes.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=func.now()),

        sa.UniqueConstraint('user_id', 'quote_id', name='uq_mino_like_user_quote'),
        sa.Index('idx_mino_like_hash', sa.func.md5(sa.cast('user_id', sa.String) + sa.cast('quote_id', sa.String))),
        sa.Index('idx_mino_like_created_at', 'created_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MinoLikes')
    # ### end Alembic commands ###
